import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

/**
 * Manual guides + changelog; API tree is generated by TypeDoc into `docs/api`.
 */
const sidebars: SidebarsConfig = {
	docsSidebar: [
		{
			type: "category",
			label: "Guides",
			collapsed: false,
			items: ["guides/getting-started", "guides/architecture", "guides/roadmap"],
		},
		"changelog",
		{
			type: "category",
			label: "API Reference",
			collapsed: true,
			link: {
				type: "doc",
				id: "api/index",
			},
			items: [
				{
					type: "autogenerated",
					dirName: "api",
				},
			],
		},
	],
};

export default sidebars;
